config/routes.rb
Rails.application.routes.draw do
  
  get '/', to: 'experiences#search'
  
  resources :bookings
  resources :users

  get '/bookings/new' => 'bookings#new', :as => :new
  
	resources :experiences do 
	 # Activities belong to CERTAIN experiences....

	 	resources :activities
	end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # resources :users do
		# # member do  	# A member depends on the id presented to generate a view. 
		# # 			# So it acts on a single object. In this case, the single merchant
		# # 	# get :tours
		# # end
  #  end
end

app/models/booking.rb
class Booking < ApplicationRecord
	belongs_to :user
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
    
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit

  end

  # POST /bookings
  # POST /bookings.json
  def create

    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        
      else
        format.html { render :new }
        
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        
      else
        format.html { render :edit }
        
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
     
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:user_id, :experience_id, :trip_date)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for(booking) do |f| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit class: "submit-booking" %>
  </div>
<% end %>

app/views/bookings/_new.html.erb
<div class="modal-header">
   <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
   <h3 id="myModalLabel">Modal header</h3>
 </div>

 <div class="modal-body">
	<%= form_for :booking, :url=>{:action => "create"}, method: :post do |f| %>
	<p>
	<%= f.label :experience %><br>
    <%= f.text_field :experience_id, :required =>true, class: 'form-control', disabled: "disabled" %><br>
   
    <%= f.label :price %><br>
    <%= f.number_field :price, :required =>true, class: 'form-control', disabled: "disabled"  %><br>
    <%= f.label :date %><br>
    <%= f.date_field :trip_date, :required =>true, class: 'form-control' %><br>
    
	</p>
	<p>
	
	</p>
	<% end %>
	</div>
	
	<div class="modal-footer">
   <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
   <button class="btn btn-primary">Save changes</button>
 </div>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', onclick: 'payWithPaystack()', new_booking_path %>

app/views/bookings/new.html.erb
<script type="text/javascript" src="https://js.paystack.co/v1/inline.js"> </script>

<p id="notice"><%= notice %></p>
<h1>New Booking</h1>

<%= form_for :booking, :url=>{:action => "create"}, method: :post do |f| %>
	<p>
	<%= f.label :experience %><br>
    <%= f.text_field :experience_id, :value => (Experience.find_by_id(params[:experience_id]).title), :required =>true, class: 'form-control', disabled: "disabled" %><br>
   
    <%= f.label :price %><br>
    <%= f.number_field :price, :value => (Experience.find_by_id(params[:experience_id]).price), :required =>true, class: 'form-control', disabled: "disabled"  %><br>
    <%= f.label :date %><br>
    <%= f.date_field :trip_date, :required =>true, class: 'form-control' %><br>
    
	</p>
	<p>
	<%= f.submit class: "submit-booking" %>
	<%= link_to "book here", "https://paystack.com/pay/devqPNGH7p" %>
	
	</p>
	<% end %>
	<script type="text/javascript">
	
	function transactionCode(len){
     var text = "T";
    
     var charset = "0123456789";
    
      for( var i=0; i < len; i++ )
        
        text += charset.charAt(Math.floor(Math.random() * charset.length));
    
     return text;
     
    }

	$('.submit-booking').click(function(e){
		e.preventDefault();
		var handler = PaystackPop.setup({
      key: '<%= ENV['PAYSTACK_PUBLIC_KEY'] %>',
      email: 'customer@email.com',
      amount: $('#booking_price').val(),
      ref: transactionCode(16),
      experience: $('#experience_id').val(),
      metadata: {
         
      },
      callback: function(response){
          alert('success. transaction ref is ' + response.reference);
      },
      onClose: function(){
          alert('window closed');
      }
    });
    handler.openIframe();	

	})


</script>

app/views/bookings/new.js.erb
$("#modal-window").html("<%= escape_javascript(render 'new') %>");
$('#modal-window').modal('show');

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Showing Your Booking</h1>
<table>
	<thead>
		<tr>
		<td>
		 Booking ID
		</td>
		<td>
		Booked Date
		</td>
	</thead>
	<tbody>
		<tr>
			<td><%= @booking.id %></td>
	        <td><%= @booking.trip_date %></td>
	        
		</tr>

	</tbody>
</table>