config/routes.rb
Rails.application.routes.draw do
  
  get '/', to: 'experiences#search'
  
  resources :bookings
  resources :users

  get '/bookings/new' => 'bookings#new', :as => :new
  
	resources :experiences do 
	 # Activities belong to CERTAIN experiences....

	 	resources :activities
	end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # resources :users do
		# # member do  	# A member depends on the id presented to generate a view. 
		# # 			# So it acts on a single object. In this case, the single merchant
		# # 	# get :tours
		# # end
  #  end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :bookings
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        # TODO: Change redirection of newly created USER!
        format.html { redirect_to @user, notice: 'User was successfully created.' } 
        
      else
        format.html { render :new, notice: 'Error: User was not created.' }
        
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        
      else
        format.html { render :edit, notice: 'User was not updated.' }
        
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name,:email,:birthday,:telephone, :Country, :city, :description, :education)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= form_for :user, url: user_path(@user), method: :patch do |f| %>

		<% if  @user.errors.any? %>
			<div id="error_explanation" >
			<h2>
		<!--pluralize has no space between e( KEEP IT LOCKED  -->
			<%= pluralize(@user.errors.count, "error") %>
				stopped it
			</h2>
		<ul>
		<% @user.errors.full_messages.each do |m| %>
		<li> <%= m %> </li>
		<% end %>
		</ul>
		</div>
		<% end %>

		<p>
		<%= f.label :name%> <br>
		<%= f.text_field :name, class: 'form-control' %>
		</p>

		<p>
		<%= f.label :email %><br>
		<%= f.email_field :email, class: 'form-control' %>
		</p>
		<p>
			<%= f.label :avatar %><br>
    		<%= f.text_field :avatar, class: 'form-control' %><br>
    
		</p>
		<p>
			<%= f.label :birthday %><br>
    		<%= f.date_field :birthday, class: 'form-control' %><br>
    
		</p>
		<p>
			 <%= f.label :telephone %><br>
             <%= f.text_field :telephone, class: 'form-control' %><br>
    
		</p>
		<p>
			 <%= f.label :city %><br>
             <%= f.text_field :city, class: 'form-control' %><br>
    
		</p>
		<p>
			 <%= f.label :country %><br>
             <%= f.text_field :Country, class: 'form-control' %><br>
    
		</p>
		<p>
			 <%= f.label :city %><br>
             <%= f.text_field :city, class: 'form-control' %><br>
    
		</p>
		<p>
			 <%= f.label :description %><br>
             <%= f.text_field :description, class: 'form-control' %><br>
    
		</p>
		<p>
			<%= render 'form', user: @user %>
			
		</p>
		<% end %>



<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.birthday %></td>
        <td><%= user.avatar %></td>
        <td><%= user.telephone %></td>
        <td><%= user.city %></td>
        <td><%= user.Country %></td>
        <td><%= user.description %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="wrapper container">
<div class = "row">
    <div class="col-md-3">
    <span></span>
    </div>
    <div class="col-md-6"> 
    <h1>Sign-up</h1>

    <%= form_for :user, url: users_path do |f| %>
	<p>
		<%= f.label :name %><br>
    <%= f.text_field :name, :required =>true, class: 'form-control' %><br>
    <%= f.label :email %><br>
    <%= f.text_field :email, :required =>true, class: 'form-control' %><br>
    <%= f.label :Birthday %><br>
    <%= f.date_field :birthday, :required =>true, class: 'form-control' %><br>
    <%= f.label :Telephone_number %><br>
    <%= f.text_field :telephone, :required =>true, class: 'form-control' %><br>
    <%= f.label :Country %><br>
    <%= f.text_field :Country, :required =>true, class: 'form-control' %><br>
    <%= f.label :City %><br>
    <%= f.text_field :city, :required =>true, class: 'form-control' %><br>
    <%= f.label :Description %><br>
    <%= f.text_field :description, :required =>true, class: 'form-control' %><br>
    <%= f.label :Education %><br>
    <%= f.text_field :education, :required =>true, class: 'form-control' %><br>
    
	</p>
	<p>
		<%= f.submit "Sign Up", class: "btn btn-primary" %>
        
	</p>
	<% end %>
    </div><%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Showing New User</h1>
<table>
	<thead>
		<tr>
		<td>
		 Name
		</td>
		<td>
		Birthday
		</td>
		<td>
		 Avatar
		</td>
		<td>
		 Telephone
		</td>
		<td>
		City
		</td>
		<td>
		 Country
		</td>
		<td>
		Description
		</td>
	</thead>
	<tbody>
		<tr>
			<td><%= @user.name %></td>
	        <td><%= @user.birthday %></td>
	        <td><%= @user.avatar %></td>
	        <td><%= @user.telephone %></td>
	        <td><%= @user.city %></td>
	        <td><%= @user.Country %></td>
	        <td><%= @user.description %></td>
		</tr>

	</tbody>
</table>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>