config/routes.rb
Rails.application.routes.draw do
  
  get '/', to: 'experiences#search'
  
  resources :bookings
  resources :users

  get '/bookings/new' => 'bookings#new', :as => :new
  
	resources :experiences do 
	 # Activities belong to CERTAIN experiences....

	 	resources :activities
	end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # resources :users do
		# # member do  	# A member depends on the id presented to generate a view. 
		# # 			# So it acts on a single object. In this case, the single merchant
		# # 	# get :tours
		# # end
  #  end
end

app/models/experience.rb
class Experience < ApplicationRecord
	has_many :activities
	mount_uploader :poster_url, PosterUrlUploader
	include PgSearch

	pg_search_scope :search_for,
	                 against: %i(title country),
	                 using: {tsearch: {prefix: true}}

	# def self.search(search)
	# 	where("country LIKE?", "%#{search}%") # Ruby is a bitch when it comes to brackets and spaces!
 #    end
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :set_experience, only: [:show, :edit, :update, :destroy]

  # GET /experiences
  # GET /experiences.json
  def index
     
    if params[:search].present?
       
       @experiences = Experience.search_for(params[:search])

    else
      
      @experiences = Experience.all
    end
   
  end

  
  # GET /experiences/1
  # GET /experiences/1.json
  def show
    @experiences = Experience.find(params[:id])
  end

  # GET /experiences/new
  def new
    @experience = Experience.new
  end

  # GET /experiences/1/edit
  def edit
  end

  # POST /experiences
  # POST /experiences.json
  def create
    @experience = Experience.new(experience_params)
   # @experience.poster_url = params[experience]

    respond_to do |format|
      if @experience.save
        format.html { redirect_to @experience, notice: 'Experience was successfully created.' }
       
      else
        format.html { render :new }
        
      end
    end
  end

  # PATCH/PUT /experiences/1
  # PATCH/PUT /experiences/1.json
  def update
    respond_to do |format|
      if @experience.update(experience_params)
        format.html { redirect_to @experience, notice: 'Experience was successfully updated.' }
        
      else
        format.html { render :edit }
        
      end
    end
  end

  # DELETE /experiences/1
  # DELETE /experiences/1.json
  def destroy
    @experience.destroy
    respond_to do |format|
      format.html { redirect_to experiences_url, notice: 'Experience was successfully destroyed.' }
      
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experience
      @experience = Experience.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def experience_params
      params.require(:experience).permit(:title, :tagline, :poster_url, :description, :notes, :provided, :deadline,:price, :country, :search,:poster_url_cache)
    end
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/views/experiences/_experiences.html.erb
<% @experiences.each do |experience| %>

<%= experience.title %>
<%= experience.tagline %>

<% end %>

app/views/experiences/_form.html.erb
<%= form_for(experience) do |f| %>
  <% if experience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(experience.errors.count, "error") %> prohibited this experience from being saved:</h2>

      <ul>
      <% experience.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit class: "submit-experience" %>
  </div>
<% end %>

app/views/experiences/edit.html.erb
<h1>Editing Experience</h1>

<%= render 'form', experience: @experience %>

<%= link_to 'Show', @experience %> |
<%= link_to 'Back', experiences_path %>

app/views/experiences/index.html.erb
<p id="notice"><%= notice %></p>
<body style="background-color: #E0E3DA";>
 <div class="about-w3bnr">
    <!-- header -->
    <div class="header">
      <!-- navigation -->
      <div style="background-color: #0c343d" class="navigation agiletop-nav">
        <div class="container">
          
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header w3l_logo">
              <button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <h1><a href="/">Safaree<span>Africa</span></a></h1>
            </div>
            <div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
              
            </div>
            <div class="cart cart box_1">
              <form action="#" method="post" class="last">
                <input type="hidden" name="cmd" value="_cart" />
                <input type="hidden" name="display" value="1" />
                <button class="w3view-cart" type="submit" name="submit" value=""><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></button>
              </form>
            </div>
          
        </div>
      </div>
      <!-- //navigation -->
    </div>

    <div class="products">
      <div class="container">
        <div class="col-md-9 product-w3ls-right">
          <div class="product-top">
            <h4><%= @experiences.count %> Experiences</h4>
            <ul>
              <li class="dropdown head-dpdn">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Filter By<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Low price</a></li>
                  <li><a href="#">High price</a></li>
                  <li><a href="#">Latest</a></li>
                </ul>
              </li>
            </ul>
            <div class="clearfix"> </div>
          </div>
        
         <div class="row">
         <% @experiences.each do |experience| %>
          <div class="col-md-12">
            <div class="mg-avl-room">
              <div class="row">
                <div class="col-sm-5">
                <%= link_to image_tag(experience.poster_url.url, class: "img-responsive"), experience %>  
                </div>
                <div class="col-sm-7">
                  <h3 class="mg-avl-room-title"><%= experience.title %> <span style="float: right">$<%= experience.price %></span></h3>
                    <p><%= experience.description %></p>
                  <div class="row mg-room-fecilities">
                    <p><%= experience.country %></p>
                  </div>
                 
                    <%= link_to "Book Now", experience, {:class => "btn btn-main pull-right"} %>
                    
                  </div>
              </div>
            </div>
          </div>
          <% end %>
        </div>

        <!-- TODO: Modal for bookings -->
        <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          
         
        </div>

        <!-- Modal for bookings -->
          <!--Side-bar -->
        </div>
        <div class="col-md-3 rsidebar">
          <div class="rsidebar-top">
            <div class="slider-left">
              <h4>Price</h4>
              <div class="row row1 scroll-pane">
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>$ 100</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>$ 200 - 300</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Over $ 300</label>
              </div>
            </div>
            <div class="sidebar-row">
              <div class="clearfix"> </div>
              <!-- script for tabs -->
              
                
             
              <!-- script for tabs -->
            </div>
            <div class="sidebar-row">
              <h4>Categories</h4>
              <div class="row row1 scroll-pane">
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>History</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Beaches</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Hiking</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Neighborhood</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Nightlife</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Shopping</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Workshop</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Arts and Streetarts</label>
              </div>
            </div>

          </div>
        </div>
        
      </div>
      <div class="clearfix"> </div>
  </div>
    </div>
</body>

    <div class="modal video-modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModal1">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        </div>
        <section>
          <div class="modal-body">
            <div class="col-md-5 modal_body_left">
              <%= image_tag("s1.jpg", class: "img-responsive") %>
             </div>
            <div class="col-md-7 modal_body_right single-top-right">
              <h3 class="item_name">France Special Dish</h3>
              <p>Proin placerat urna et consequat efficitur, sem odio blandit enim</p>
              <div class="single-rating">
                <ul>
                  <li><i class="fa fa-star-o" aria-hidden="true"></i></li>
                  <li><i class="fa fa-star-o" aria-hidden="true"></i></li>
                  <li><i class="fa fa-star-o" aria-hidden="true"></i></li>
                  <li><i class="fa fa-star-o" aria-hidden="true"></i></li>
                  <li class="w3act"><i class="fa fa-star-o" aria-hidden="true"></i></li>
                  <li class="rating">20 reviews</li>
                  <li><a href="#">Add your review</a></li>
                </ul>
              </div>
              <div class="single-price">
                <ul>
                  <li>$18</li>
                  <li><del>$20</del></li>
                  <li><span class="w3off">10% OFF</span></li>
                  <li>Ends on : Dec,5th</li>
                  <li><a href="#"><i class="fa fa-gift" aria-hidden="true"></i> Coupon</a></li>
                </ul>
              </div>
              <p class="single-price-text">Fusce a egestas nibh, eget ornare erat. Proin placerat, urna et consequat efficitur, sem odio blandit enim, sit amet euismod turpis est mattis lectus. Vestibulum maximus quam et quam egestas imperdiet. In dignissim auctor viverra. </p>
              <form action="#" method="post">
                <input type="hidden" name="cmd" value="_cart" />
                <input type="hidden" name="add" value="1" />
                <input type="hidden" name="w3ls_item" value="France Special" />
                <input type="hidden" name="amount" value="18.00" />
                <button type="submit" class="w3ls-cart"><i class="fa fa-cart-plus" aria-hidden="true"></i> Add to cart</button>
              </form>
              <a href="#" class="w3ls-cart w3ls-cart-like"><i class="fa fa-heart-o" aria-hidden="true"></i> Add to Wishlist</a>
              <div class="single-page-icons social-icons">
                <ul>
                  <li>
                    <h4>Share on</h4></li>
                  <li>
                    <a href="#" class="fa fa-facebook icon facebook"> </a>
                  </li>
                  <li>
                    <a href="#" class="fa fa-twitter icon twitter"> </a>
                  </li>
                  <li>
                    <a href="#" class="fa fa-google-plus icon googleplus"> </a>
                  </li>
                  <li>
                    <a href="#" class="fa fa-dribbble icon dribbble"> </a>
                  </li>
                  <li>
                    <a href="#" class="fa fa-rss icon rss"> </a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="clearfix"> </div>
          </div>
        </section>
      </div>
    </div>
  </div>
</div>
    </div>
  </div>

  <div class="subscribe agileits-w3layouts">
    <div class="container">
      <div class="col-md-12 subscribe-right">
        <h3 class="w3ls-title">Subscribe to Our <br><span>Newsletter</span></h3>
        <form action="#" method="post">
          <input type="email" name="email" placeholder="Enter your Email..." required="">
          <input type="submit" value="Subscribe">
          <div class="clearfix"> </div>
        </form>
        <!--<img src="images/i1.png" class="sub-w3lsimg" alt="" />-->
      </div>
      <div class="clearfix"> </div>
    </div>
  </div>

<div class="copyw3-agile">
    <div class="container">
      <p>&copy; 2017 Safaree Africa. All rights reserved </p>
    </div>
  </div>

app/views/experiences/new.html.erb
<h1>New Experience</h1>


    <%= form_for :experience, url: experiences_path do |f| %>
	<p>
	<%= f.label :title %><br>
    <%= f.text_field :title, :required =>true, class: 'form-control' %><br>
    
    <%= f.label :tagline%><br>
    <%= f.text_field :tagline, :required =>true, class: 'form-control' %><br>
    
    <%= f.label :poster_url %><br>
    <%= f.file_field :poster_url, :required =>true, class: 'form-control' %><br>
    
    <%= f.hidden_field(:poster_url_cache) %>

    <%= f.label :provided %><br>
    <%= f.text_area :provided, :required =>true, class: 'form-control' %><br>
   
    <%= f.label :notes %><br>
    <%= f.text_area :notes, :required =>true, class: 'form-control' %><br>

    <%= f.label :Description %><br>
    <%= f.text_area :description, :required =>true, class: 'form-control' %><br>
    
    <%= f.label :price %><br>
    <%= f.number_field :price, :required =>true, class: 'form-control' %><br>

    <%= f.label :deadline %><br>
    <%= f.date_field :deadline, :required =>true, class: 'form-control' %><br>

     <%= f.label :country %><br>
    <%= f.text_field :country, :required =>true, class: 'form-control' %><br>

    </p>
	<p>
		<%= render 'form', experience: @experience %>
        
	</p>
	<% end %>


<%= link_to 'Back', experiences_path %>

app/views/experiences/search.html.erb
<body>
<!-- banner -->
	<div class="banner container-fluid">
		<!-- header -->
		<div class="header ">
			<!-- navigation -->
			<div  class="navigation agiletop-nav">
				<div class="container">
					<nav class="navbar navbar-default">
						<!-- Brand and toggle get grouped for better mobile display -->
						<div class="navbar-header w3l_logo">
							<button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
							<h1> <%= link_to image_tag("safaree-v6-2.png"), "/" %></h1>
						</div>
						<div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
							<ul class="nav navbar-nav navbar-right">
								<li class="header-button"><a href="index.html" >Sign up</a></li>
								<li class="header-button"><a href="index.html">Log in</a></li>
							</ul>
						</div>
					</nav>
				</div>
			</div>
			<!-- //navigation -->
		</div>
		<!-- //header-end -->
		<!-- banner-text -->
		<div class="banner-text">
			<div class="container">
				<h2> <span> Discover & Book unique experiences driven by locals</span></h2>
				
				<%= form_tag(experiences_path, method: :get, id: "search-form") do %>
				  <div class="agileits_search">
                      <%= text_field_tag :search, params[:search] %>

                      <%= submit_tag "Search" %>
                    </div>
               <% end %>	
			<br>
			<br>
			<br>
			<br>
			<br>
			<br>
		</div>
	</div>
	<!-- add-products -->
	

	</div>

	<div class="add-products">
		<div class="container-fluid">
			<div class="row add-products-row">
				<div class="col-md-4 col-sm-6 w3ls-add-grids lagos">
					<a href="menu.html">
						<h4 style="color: white">Lagos</h4>
					</a>
				</div>
				<div class="col-md-4 col-sm-6 w3ls-add-grids w3ls-add-grids-right accra">
					<a href="experiences">
						<h4 style="color: white">Accra</h4>
					</a>
				</div>
				<div class="col-md-4 col-sm-6 w3ls-add-grids w3ls-add-grids-right lome">
					<a href="menu.html">
						<h4 style="color: white">Lome</h4>
					</a>
				</div>
				<div style="margin-bottom: 20px" class="clearfix"> </div>

			<div >
				<div class="col-sm-6 w3ls-add-grids cotonou">
					<a href="menu.html">
						<h4 style="color: white">Cotonou</h4>
					</a>
				</div>
				<div class="col-sm-6 w3ls-add-grids w3ls-add-grids-right kakum">
					<a href="menu.html">
						<h4 style="color: white">Kakum</h4>
					</a>
				</div>
				<div class="col-sm-6 w3ls-add-grids w3ls-add-grids-right abuja">
					<a href="menu.html">
						<h4 style="color: white">Abuja</h4>
					</a>
				</div>
			</div>

				
			</div>

				<div class="clearfix"> </div>
		</div>
	</div>


	<!-- subscribe -->
	<div class="subscribe agileits-w3layouts">
		<div class="container">
	
			
			<div class="col-md-12 subscribe-right">
				<h3 class="w3ls-title">Subscribe to Our <br><span>Newsletter</span></h3>
				<form action="#" method="post">
					<input type="email" name="email" placeholder="Enter your Email..." required="">
					<input type="submit" value="Subscribe">
					<div class="clearfix"> </div>
				</form>
				<!--<img src="images/i1.png" class="sub-w3lsimg" alt="" />-->
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
	<!-- //subscribe -->

</body>

<script type="text/javascript">
$("#search").autocomplete({
source: function (request, response) {
    $.ajax({
        url: "/experiences",
        data: { query: request },
        success: function (data) {
            $this.val(data);
        },
        error: function () {
            alert('oops')
        }
    });
});	
</script>

app/views/experiences/show.html.erb
<p id="notice"><%= notice %></p>

<div class="header">
			<!-- navigation -->
			<div  class="navigation agiletop-nav">
				<div class="container">
					<nav class="navbar navbar-default">
						<!-- Brand and toggle get grouped for better mobile display -->
						<div class="navbar-header w3l_logo">
							<button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
							<h1> <%= image_tag("safaree-v6-2.png") %></h1>
						</div>
						<div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
							<ul class="nav navbar-nav navbar-right">
								<li class="header-button"><a href="index.html" >Sign up</a></li>
								<li class="header-button"><a href="index.html">Log in</a></li>
							</ul>
						</div>
					</nav>
				</div>
			</div>
			<!-- //navigation -->
		</div>
       
       <div class="privacy about">
		<div class="experience-details">
			<div class="container">
				<div class="row">
					<div class="experience-banner col-md-12">
						<%= image_tag(@experience.poster_url.url(:standard)) %>
						
						<div class="inner-info">
							<p>$<%= @experience.price %><p>
							
							<%= link_to "Book Now",{:controller => "bookings", :action => "new", :experience_id => params[:id],:users_id => 2}, 
							{ :style => 'border-color: #e67e22; background-color: #e67e22; 
									border-radius: 0px; padding: 8px; width: 100%; margin: 0 auto', :class =>'btn btn-primary'} %>
						</div>
					</div>
				</div>

				<div class="row">
					<div style="padding-right: 150px" class="col-md-12">
						<h1 style="margin-top: 20px" ><%= @experience.title %></h1>
						<h2 style="margin-top: 20px" ><%= @experience.tagline %></h2>
						<p>
						<%= @experience.description %>
						</p>

				<div style="margin-top: 40px" class="lower">
					<h3 style="padding-top: 20px" >What you will do</h3>
					<ul style="padding: 10px; background-color: #fff; margin-right: 200px">
						<li style="background-color: #fff"><%= @experience.provided %> </li>
						<li style="background-color: #fff"><%= @experience.notes %> </li>
						  </li>
					</ul>
						<p> The Booking Deadline is :<%= @experience.deadline %> </p>
				</div>

						<p> Your guide will be <%= label_tag User.find_by_id(@experience.user_id).name %><br>
							Likes: <%= label_tag User.find_by_id(@experience.user_id).description %> <br>

					</div>
					<!--<div style="background-color: white" class = "col-md-5">
						<h3>What you will do</h3>
					</div>-->
				</div>

				</div>
			</div>
		</div>