config/routes.rb
Rails.application.routes.draw do
  
  get '/', to: 'experiences#search'
  
  resources :bookings
  resources :users

  get '/bookings/new' => 'bookings#new', :as => :new
  
	resources :experiences do 
	 # Activities belong to CERTAIN experiences....

	 	resources :activities
	end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # resources :users do
		# # member do  	# A member depends on the id presented to generate a view. 
		# # 			# So it acts on a single object. In this case, the single merchant
		# # 	# get :tours
		# # end
  #  end
end

app/models/activity.rb
class Activity < ApplicationRecord
	belongs_to :experience

	# NOTICE: mount_uploaders is pluralized for multiple file uploads
	mount_uploaders :pictures, PicturesUploader 
	
	
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @activity = Activity.find(params[:id])
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    
    @activity = Activity.new(activity_params)

    @activity.experience_id = params[:experience_id]
    
    respond_to do |format|

      if @activity.save
        format.html { redirect_to experience_activities_path, notice: 'Activity was successfully created.' }
        
      else
        format.html { render :new , notice: @activity.errors.full_messages }
       
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:title, :start_time, :end_time, :date, {pictures: []}, :price)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for(activity) do |f| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= form_for :activity, url: experience_activity_path(@activity), method: :patch do |f| %>

		<% if  @activity.errors.any? %>
			<div id="error_explanation" >
			<h2>
		<!--pluralize has no space between e( KEEP IT LOCKED  -->
			<%= pluralize(@activity.errors.count, "error") %>
				stopped it
			</h2>
		<ul>
		<% @activity.errors.full_messages.each do |m| %>
		<li> <%= m %> </li>
		<% end %>
		</ul>
		</div>
		<% end %>

		<p>
		<%= f.label :title %> <br>
		<%= f.text_field :title, class: 'form-control' %>
		</p>

		<p>
		<%= f.label :start_time %><br>
		<%= f.time_field :start_time, :ignore_date => true, class: 'form-control' %>
		</p>
		<p>
			<%= f.label :end_time %><br>
    		<%= f.time_field :end_time, :ignore_date => true, class: 'form-control' %><br>
    
		</p>
		<p>
			<%= f.label :date %><br>
    		<%= f.date_field :date, class: 'form-control' %><br>
    
		</p>
		<p>
			<%= f.label :Picture %><br>
    		<%= f.text_field :pic1_url, class: 'form-control' %><br>
    
		</p>
		<p>
			 <%= f.label :Picture %><br>
             <%= f.text_field :pic2_url, class: 'form-control' %><br>
    
		</p>
		<p>
			 <%= f.label :Picture %><br>
             <%= f.text_field :pic3_url, class: 'form-control' %><br>
    
		</p>
		<p>
			 <%= f.label :location %><br>
             <%= f.text_field :location, class: 'form-control' %><br>
    
		</p>
		<p>
			 <%= f.label :price %><br>
             <%= f.number_field :price, class: 'form-control' %><br>
    
		</p>
		<p>
			<%= render 'form', activity: @activity %>
			
		</p>
		<% end %>

<%= link_to 'Show', @experience_activity %> |
<%= link_to 'Back', experience_activities_path %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Activities</h1>

<table>
  <thead>
    <tr>
      <th colspan="3">All Activities </th>
    </tr>
    <tr>
    <td>
     Title
    </td>
    <td>
    Date
    </td>
    <td>
     Start Time
    </td>
    <td>
    End Time
    </td>
    <td>
     Picture
    </td>
    <td>
    Picture
    </td>
    <td>
    Picture
    </td>
    <td>
    Location
    </td>
    <td>
    Price
    </td>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
      
       <td><%= activity.title %></td>
       <td><%= activity.date %></td>
        <td><%= activity.start_time %></td>
        <td><%= activity.end_time %></td>
        <td></td>
        <td><%= activity.location %></td>
        <td><%= activity.price   %></td>
        <%= image_tag activity.pictures %>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_experience_activity_path %>

app/views/activities/new.html.erb
<p id="notice"><%= notice %></p>
<h1>New Activity</h1>

<%= form_for :activity, multipart: true, data: {'abide' => true}, url: experience_activities_path do |f| %>
	<p>
		<%= f.label :title %><br>
    <%= f.text_field :title, :required =>true, class: 'form-control' %><br>
    <%= f.label :start_time %><br>
    <%= f.time_field :start_time, :required =>true, class: 'form-control' %><br>
    <%= f.label :end_time %><br>
    <%= f.time_field :end_time, :required =>true, class: 'form-control' %><br>
    <%= f.label :pictures %><br>
    <%= f.file_field :pictures, :required =>true, multiple: true, class: 'form-control' %><br>
    <%= f.label :date %><br>
    <%= f.date_field :date, :required =>true, class: 'form-control' %><br>
    <%= f.label :price %><br>
    <%= f.number_field :price, :required =>true, class: 'form-control' %><br>
    
	</p>
	<p>
	
		<%= f.submit "Create Activity",class: 'btn btn-primary' %>
	</p>
	<% end %>

<%= link_to 'Back', experience_activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Showing New Activities</h1>
<table>
	<thead>
		<tr>
		<td>
		 Title
		</td>
		<td>
		Date
		</td>
		<td>
		 Start Time
		</td>
		<td>
		End Time
		</td>
		<td>
		 Picture
		</td>
		<td>
		Picture
		</td>
		<td>
		Picture
		</td>
		<td>
		Price
		</td>
	</thead>
	<tbody>
		<tr>
			<td><%= @activity.title %></td>
	        <td><%= @activity.date %></td>
	        <td><%= @activity.start_time %></td>
	        <td><%= @activity.end_time %></td>
	        <td><%= @activity.pictures%></td>
	        <td><%= @activity.price %></td>
		</tr>

	</tbody>
</table>
		
<%= link_to 'Edit', edit_experience_activity_path(@activity) %> |
<%= link_to 'Back', experience_activities_path %>